# Generated by Django 6.0.2 on 2026-02-23 17:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjetoPrecificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('configuracao_variaveis', models.JSONField(default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to='accounts.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoPrecificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_produto', models.CharField(max_length=100)),
                ('elasticidade', models.FloatField()),
                ('r_squared', models.FloatField(blank=True, null=True)),
                ('shapiro_p_value', models.FloatField(blank=True, null=True)),
                ('detalhes_variaveis', models.JSONField(default=dict)),
                ('custo_unitario', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('preco_atual', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('preco_sugerido', models.FloatField(blank=True, null=True)),
                ('margem_projetada', models.FloatField(blank=True, null=True)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='projects.projetoprecificacao')),
            ],
            options={
                'unique_together': {('projeto', 'codigo_produto')},
            },
        ),
    ]
