# Generated by Django 6.0.2 on 2026-02-24 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendaHistoricaDW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_produto', models.CharField(max_length=100)),
                ('nome_produto', models.CharField(blank=True, max_length=255, null=True)),
                ('data_venda', models.DateField()),
                ('quantidade', models.FloatField()),
                ('preco_praticado', models.FloatField()),
                ('custo_unitario', models.FloatField(blank=True, null=True)),
                ('variaveis_extras', models.JSONField(blank=True, default=dict)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendas_dw', to='accounts.empresa')),
                ('projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.projetoprecificacao')),
            ],
            options={
                'verbose_name': 'Venda Histórica (DW)',
                'verbose_name_plural': 'Vendas Históricas (DW)',
                'indexes': [models.Index(fields=['empresa', 'codigo_produto', 'data_venda'], name='projects_ve_empresa_0c8d9e_idx')],
                'unique_together': {('empresa', 'codigo_produto', 'data_venda')},
            },
        ),
    ]
