# Generated by Django 6.0.2 on 2026-02-25 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_vendahistoricadw'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadoprecificacao',
            name='revisado_pelo_usuario',
            field=models.BooleanField(default=False),
        ),
    ]
