# Generated by Django 6.0.2 on 2026-02-26 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('projects', '0003_resultadoprecificacao_revisado_pelo_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrevisaoDemanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_produto', models.CharField(max_length=100)),
                ('data_geracao', models.DateTimeField(auto_now_add=True)),
                ('dados_previsao', models.JSONField(default=dict, help_text='Datas futuras e quantidades previstas')),
                ('explicabilidade_shap', models.JSONField(default=dict, help_text='Impacto percentual de cada variável')),
                ('acuracia_r2', models.FloatField(blank=True, null=True)),
                ('erro_medio', models.FloatField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.empresa')),
            ],
            options={
                'verbose_name': 'Previsão de Demanda',
                'verbose_name_plural': 'Previsões de Demanda',
            },
        ),
    ]
