# Generated by Django 6.0.2 on 2026-02-26 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('projects', '0004_previsaodemanda'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrevisaoFaturamentoMacro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_geracao', models.DateTimeField(auto_now_add=True)),
                ('dados_forecast', models.JSONField(default=dict, help_text='Previsão de Receita (yhat, yhat_lower, yhat_upper)')),
                ('componentes_sazonalidade', models.JSONField(default=dict, help_text='Tendência, Sazonalidade Semanal e Anual')),
                ('faturamento_projetado_total', models.FloatField(default=0, help_text='Soma da receita prevista no período')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.empresa')),
            ],
            options={
                'verbose_name': 'Previsão de Faturamento',
                'verbose_name_plural': 'Previsões de Faturamento',
            },
        ),
    ]
