# Generated by Django 6.0.2 on 2026-03-02 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('projects', '0005_previsaofaturamentomacro'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaturamentoEmpresaDW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_faturamento', models.DateField()),
                ('faturamento_total', models.FloatField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.empresa')),
            ],
            options={
                'verbose_name': 'Faturamento Macro',
                'verbose_name_plural': 'Faturamentos Macro',
                'unique_together': {('empresa', 'data_faturamento')},
            },
        ),
    ]
