# Generated by Django 6.0.2 on 2026-03-10 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_empresa_is_active_subscriber_and_more'),
        ('projects', '0006_faturamentoempresadw'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Filial RJ-Centro', max_length=255)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lojas', to='accounts.empresa')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='faturamentoempresadw',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='faturamentoempresadw',
            name='loja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faturamentos_macro', to='projects.loja'),
        ),
        migrations.AddField(
            model_name='projetoprecificacao',
            name='loja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projetos_pricing', to='projects.loja'),
        ),
        migrations.AddField(
            model_name='vendahistoricadw',
            name='loja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendas_dw', to='projects.loja'),
        ),
        migrations.AlterUniqueTogether(
            name='faturamentoempresadw',
            unique_together={('empresa', 'loja', 'data_faturamento')},
        ),
        migrations.CreateModel(
            name='EventoCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Aniversário da Loja, Feriado Municipal', max_length=255)),
                ('data_evento', models.DateField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='accounts.empresa')),
                ('loja', models.ForeignKey(blank=True, help_text='Deixe em branco se for um evento global', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='projects.loja')),
            ],
            options={
                'verbose_name': 'Evento de Calendário',
                'verbose_name_plural': 'Eventos de Calendário',
                'unique_together': {('empresa', 'loja', 'nome', 'data_evento')},
            },
        ),
    ]
