# Generated by Django 6.0.2 on 2026-03-10 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_loja_alter_faturamentoempresadw_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='previsaofaturamentomacro',
            name='loja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previsoes_macro', to='projects.loja'),
        ),
    ]
