# Generated by Django 6.0.2 on 2026-03-10 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_previsaofaturamentomacro_loja'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventocalendario',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='eventocalendario',
            name='data_fim',
            field=models.DateField(default='2024-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventocalendario',
            name='data_inicio',
            field=models.DateField(default='2024-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventocalendario',
            name='loja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='projects.loja'),
        ),
        migrations.AlterField(
            model_name='eventocalendario',
            name='nome',
            field=models.CharField(help_text='Ex: Black Week, Aniversário', max_length=255),
        ),
        migrations.RemoveField(
            model_name='eventocalendario',
            name='data_evento',
        ),
    ]
