# Generated by Django 6.0.2 on 2026-03-10 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_empresa_is_active_subscriber_and_more'),
        ('projects', '0009_alter_eventocalendario_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventocalendario',
            unique_together={('empresa', 'loja', 'nome', 'data_inicio', 'data_fim')},
        ),
    ]
