# Generated by Django 6.0.2 on 2026-03-11 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_empresa_is_active_subscriber_and_more'),
        ('projects', '0010_alter_eventocalendario_unique_together'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='vendahistoricadw',
            name='projects_ve_empresa_0c8d9e_idx',
        ),
        migrations.AlterUniqueTogether(
            name='resultadoprecificacao',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='previsaodemanda',
            name='loja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previsoes_demanda', to='projects.loja'),
        ),
        migrations.AddField(
            model_name='resultadoprecificacao',
            name='loja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resultados_precificacao', to='projects.loja'),
        ),
        migrations.AlterUniqueTogether(
            name='previsaodemanda',
            unique_together={('empresa', 'loja', 'codigo_produto', 'data_geracao')},
        ),
        migrations.AlterUniqueTogether(
            name='resultadoprecificacao',
            unique_together={('projeto', 'loja', 'codigo_produto')},
        ),
        migrations.AlterUniqueTogether(
            name='vendahistoricadw',
            unique_together={('empresa', 'loja', 'codigo_produto', 'data_venda')},
        ),
        migrations.AddIndex(
            model_name='vendahistoricadw',
            index=models.Index(fields=['empresa', 'loja', 'codigo_produto', 'data_venda'], name='projects_ve_empresa_d36be4_idx'),
        ),
    ]
