# Generated by Django 6.0.2 on 2026-03-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_remove_vendahistoricadw_projects_ve_empresa_0c8d9e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadoprecificacao',
            name='elasticidade_ic_lower',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resultadoprecificacao',
            name='elasticidade_ic_upper',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resultadoprecificacao',
            name='elasticidade_p_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
