# Generated by Django 5.2.12 on 2026-03-29 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_reputacao'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='analisereputacao',
            new_name='projects_an_empresa_02437b_idx',
            old_name='projects_ar_empresa_dt_idx',
        ),
        migrations.RenameIndex(
            model_name='tendenciadetectada',
            new_name='projects_te_empresa_32a295_idx',
            old_name='projects_te_empresa_arq_idx',
        ),
        migrations.AlterField(
            model_name='analisereputacao',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='analisereputacao',
            name='reviews',
            field=models.JSONField(default=list, help_text='[{autor, rating, texto, data_iso, data_relativa, sentimento, temas}]'),
        ),
        migrations.AlterField(
            model_name='analisereputacao',
            name='score_sentimento',
            field=models.IntegerField(default=0, help_text='Índice de satisfação 0–100'),
        ),
        migrations.AlterField(
            model_name='correlacaoanalise',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='eventocalendario',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='faturamentoempresadw',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='loja',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='previsaodemanda',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='previsaofaturamentomacro',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='projetoprecificacao',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='radarconfig',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='radarconfig',
            name='limiar_aceleracao',
            field=models.FloatField(default=50.0, help_text='Aceleração mínima (%) para registrar uma tendência (padrão: 50%)'),
        ),
        migrations.AlterField(
            model_name='radarconfig',
            name='palavras_chave',
            field=models.JSONField(default=list, help_text="Lista de keywords customizados para monitorar (ex: ['azeite', 'leite condensado'])"),
        ),
        migrations.AlterField(
            model_name='reputacaoconfig',
            name='google_place_foto',
            field=models.URLField(blank=True, help_text='URL da foto do lugar'),
        ),
        migrations.AlterField(
            model_name='reputacaoconfig',
            name='google_place_url',
            field=models.URLField(blank=True, help_text='Link do Google Maps'),
        ),
        migrations.AlterField(
            model_name='reputacaoconfig',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='resultadoprecificacao',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tendenciadetectada',
            name='aceleracao_por_fonte',
            field=models.JSONField(default=dict, help_text="{'google_trends': 280.0, 'newsapi': 150.0, ...}"),
        ),
        migrations.AlterField(
            model_name='tendenciadetectada',
            name='confianca',
            field=models.FloatField(default=0.5, help_text='Confiança da classificação (0–1)'),
        ),
        migrations.AlterField(
            model_name='tendenciadetectada',
            name='fontes',
            field=models.JSONField(default=list, help_text='[{fonte, mencoes_recentes, mencoes_baseline, titulos}]'),
        ),
        migrations.AlterField(
            model_name='tendenciadetectada',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tendenciadetectada',
            name='recomendacao',
            field=models.JSONField(default=dict, help_text='{preco_acao, preco_pct, estoque_acao, estoque_pct, gondola, janela_min, janela_max}'),
        ),
        migrations.AlterField(
            model_name='tendenciadetectada',
            name='skus_relacionados',
            field=models.JSONField(default=list, help_text='[{codigo_produto, nome_produto, similaridade, elasticidade}]'),
        ),
        migrations.AlterField(
            model_name='vendahistoricadw',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
