# Generated by Django 5.2.12 on 2026-03-30 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_rename_projects_ar_empresa_dt_idx_projects_an_empresa_02437b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='correlacaoanalise',
            name='ibge_dados',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
