# Generated by Django 5.2.12 on 2026-03-30 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_correlacao_ibge_dados'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisereputacao',
            name='projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analises_reputacao', to='projects.projetoprecificacao'),
        ),
        migrations.AddField(
            model_name='tendenciadetectada',
            name='projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tendencias', to='projects.projetoprecificacao'),
        ),
    ]
