# Generated by Django 6.0.2 on 2026-03-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='is_active_subscriber',
            field=models.BooleanField(default=False, help_text='Verdadeiro se a empresa tem uma assinatura paga e ativa.'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='stripe_customer_id',
            field=models.CharField(blank=True, help_text='ID do cliente no Stripe (ex: cus_12345)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, help_text='ID da assinatura ativa (ex: sub_12345)', max_length=100, null=True),
        ),
    ]
