# Generated by Django 6.0.2 on 2026-04-04 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_alter_empresa_id_alter_usuarioempresa_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concorrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Supermercados Guanabara', max_length=255)),
                ('programa_fidelidade', models.CharField(blank=True, help_text='Ex: Guana Clube, Clube Extra — ou vazio se não houver', max_length=100, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concorrentes', to='accounts.empresa')),
            ],
            options={
                'verbose_name': 'Concorrente',
                'verbose_name_plural': 'Concorrentes',
                'ordering': ['nome'],
                'unique_together': {('empresa', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='ExtraçãoEncarte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo_pdf', models.FileField(upload_to='encartes/pdfs/')),
                ('vigencia_inicio', models.DateField(help_text='Início da validade das ofertas')),
                ('vigencia_fim', models.DateField(help_text='Fim da validade das ofertas')),
                ('data_extracao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('concluido', 'Concluído'), ('erro', 'Erro')], default='pendente', max_length=20)),
                ('total_paginas', models.IntegerField(default=0)),
                ('total_produtos', models.IntegerField(default=0)),
                ('total_precos', models.IntegerField(default=0)),
                ('precos_clube', models.IntegerField(default=0)),
                ('precos_promocional', models.IntegerField(default=0)),
                ('modelo_extracao', models.CharField(default='claude-opus-4-5', max_length=100)),
                ('avisos', models.JSONField(default=list)),
                ('erro_mensagem', models.TextField(blank=True, null=True)),
                ('concorrente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracoes', to='encartes.concorrente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracoes_encarte', to='accounts.empresa')),
            ],
            options={
                'verbose_name': 'Extração de Encarte',
                'verbose_name_plural': 'Extrações de Encarte',
                'ordering': ['-data_extracao'],
            },
        ),
        migrations.CreateModel(
            name='ProdutoEncarte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagina', models.IntegerField(default=1)),
                ('nome', models.CharField(max_length=500)),
                ('marca', models.CharField(blank=True, max_length=255, null=True)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('quantidade', models.CharField(blank=True, help_text='Ex: 5kg, 500ml, pack c/12 473ml', max_length=100, null=True)),
                ('ean', models.CharField(blank=True, max_length=20, null=True)),
                ('validade_oferta', models.CharField(blank=True, max_length=100, null=True)),
                ('condicao_especial', models.CharField(blank=True, help_text='Ex: leve 3 pague 2', max_length=500, null=True)),
                ('extracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='encartes.extraçãoencarte')),
            ],
            options={
                'verbose_name': 'Produto do Encarte',
                'verbose_name_plural': 'Produtos do Encarte',
                'ordering': ['pagina', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='PrecoEncarte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('normal', 'Normal'), ('promocional', 'Promocional'), ('clube', 'Clube'), ('condicional', 'Condicional')], default='normal', max_length=20)),
                ('canal', models.CharField(blank=True, help_text='Ex: loja, app, online', max_length=50, null=True)),
                ('condicao', models.CharField(blank=True, help_text='Ex: Guana Clube, embalagem 400ml', max_length=500, null=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precos', to='encartes.produtoencarte')),
            ],
            options={
                'verbose_name': 'Preço do Encarte',
                'verbose_name_plural': 'Preços do Encarte',
                'ordering': ['tipo', 'valor'],
            },
        ),
    ]
